version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: postgis_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: StrongPass123
      POSTGRES_DB: geodb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - heatmapnet

  etl:
    build: ./etl
    container_name: etl_container
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: geodb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: StrongPass123
    networks:
      - heatmapnet

  web:
    image: nginx:alpine
    container_name: web_container
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "8000:80"
    networks:
      - heatmapnet

volumes:
  db_data:

networks:
  heatmapnet:
    driver: bridge
