services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgis_container
    environment:
      POSTGRES_DB: geodb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: StrongPass123
    volumes:
      - serverless_heatmap_db_data:/var/lib/postgresql/data
    networks: [heatmapnet]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d geodb"]
      interval: 5s
      timeout: 5s
      retries: 10

  etl:
    # ⬇⬇ Build the image from the repo root, using the Dockerfile in etl/
    build:
      context: .
      dockerfile: etl/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/data                 # where your CSV/GeoJSON live
      - ./:/app                      # (optional) hot-reload code inside container
    # If your Dockerfile already has: CMD ["python","etl/etl.py"]
    # you don't need this command line. If you want to pass args, add:
    command: ["python","etl/etl.py","--towers-csv","/data/opencellid_barbados_towers.csv"]
    networks: [heatmapnet]

  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "8000:80"
    networks: [heatmapnet]

networks:
  heatmapnet:

volumes:
  serverless_heatmap_db_data:
